# Generated by Django 5.2.7 on 2025-11-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('receiver', models.CharField(choices=[('ALL', 'Tất cả (ALL)'), ('STUDENT', 'Chỉ Sinh viên'), ('TEACHER', 'Chỉ Giảng viên')], default='ALL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Events',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
    ]
