# Generated by Django 5.2.7 on 2025-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('studentId', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fullName', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
