# Generated by Django 5.2.7 on 2025-10-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwordHash', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fullName',
            new_name='fullNameStudent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='className',
            field=models.CharField(default='chưa có', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='chưa có', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='student',
            name='userId',
            field=models.ForeignKey(default='chưa có', on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
            preserve_default=False,
        ),
    ]
