# Generated by Django 5.2.7 on 2025-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_rename_fullname_student_fullnamestudent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwordHash', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='userId',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='student',
            name='className',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.AlterField(
            model_name='student',
            name='fullNameStudent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
