# Generated by Django 5.2.7 on 2025-11-01 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_alter_student_userid_remove_student_classname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcementId', models.AutoField(primary_key=True, serialize=False)),
                ('senderRole', models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Announcements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('classId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseId', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('courseName', models.CharField(blank=True, max_length=100, null=True)),
                ('credits', models.IntegerField()),
                ('descriptions', models.TextField()),
            ],
            options={
                'db_table': 'Courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomid', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('roomNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.IntegerField()),
                ('building', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('scheduleid', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('dayOfWeek', models.CharField(blank=True, choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sum', 'Sum')], max_length=20, null=True)),
                ('weekNumber', models.IntegerField()),
            ],
            options={
                'db_table': 'Schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwordHash', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students_Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Students_Courses',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentId', models.OneToOneField(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.users')),
                ('fullName', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('className', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherId', models.OneToOneField(db_column='teacherId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.users')),
                ('fullName', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Teachers',
                'managed': False,
            },
        ),
    ]
