# Generated by Django 5.2.7 on 2025-11-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_announcements_classes_courses_rooms_schedules_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('adminId', models.OneToOneField(db_column='adminId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.users')),
                ('fullName', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('attendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('classId', models.CharField(max_length=20)),
                ('studentId', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Có mặt'), ('ABSENT', 'Vắng mặt'), ('LATE', 'Đi muộn')], default='PRESENT', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Attendances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('receiver', models.CharField(choices=[('ALL', 'Tất cả (ALL)'), ('STUDENT', 'Chỉ Sinh viên'), ('TEACHER', 'Chỉ Giảng viên')], default='ALL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Events',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('gradeId', models.AutoField(db_column='gradeId', primary_key=True, serialize=False)),
                ('attendanceScore', models.DecimalField(db_column='attendanceScore', decimal_places=2, default=0, max_digits=5)),
                ('midtermScore', models.DecimalField(db_column='midtermScore', decimal_places=2, default=0, max_digits=5)),
                ('finalScore', models.DecimalField(db_column='finalScore', decimal_places=2, default=0, max_digits=5)),
                ('totalScore', models.DecimalField(blank=True, db_column='totalScore', decimal_places=2, editable=False, max_digits=5, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students_Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Students_Classes',
                'managed': False,
            },
        ),
    ]
